#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.14.142:3306/boruomi?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: '#Wdza983264'

  data:
    redis:
      host: localhost
      password:
      port: 6379
      database: 0
cache:
  access_token_expiration_minute: 15
  refresh_token_expiration_day: 30
